name:                language-choucho
version:             0.1.0.1
github:              "ayachigin/language-choucho"
license:             BSD3
author:              "Ayachi Gin"
maintainer:          "ayachigin@gmail.com"
copyright:           "© 2017 ayachigin."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ayachigin/language-choucho#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- random
- lens

library:
  source-dirs: src

executables:
  language-choucho-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-choucho

tests:
  language-choucho-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-choucho
    - hspec
    - hspec-discover
    - parsec
    - QuickCheck

  language-choucho-doctest:
    main:                doctest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-choucho
    - doctest
    - hspec
    - QuickCheck